#!/bin/bash

arm-none-eabi-objcopy -O ihex "${1}" "${1}.hex"

arm-none-eabi-objcopy -O binary "${1}" "${1}.bin"
#arm-none-eabi-objdump -C -D -S "${1}" > "${1}.S"

cp "${1}.bin" "${1}.dfu"
dfu-suffix -v ffff -p f3c4 -a "${1}.dfu"

arm-none-eabi-size "${1}"